server:
  port: 19000

spring:
  application:
    name: server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:19000/eureka/
  instance:
    hostname: localhost